### ISSUE TITLE
Colors hardly readable in VS Light and Blue Themes

### ISSUE THREAD

**Issue by BertTank** [nbalakin/VSOutputEnhancer#1]
The default text colors are hardly readable if Visual Studio is used with another color theme than "Dark". Please consider to adjust the colors by the theme used in Visual Studio.

![output](https://cloud.githubusercontent.com/assets/3630638/11181065/aaac880c-8c5f-11e5-98a3-3a04714e5a13.png)

**Comment by BertTank** [comment]
I see you have custom resources for the different themes but it seems to me that the logic to retrieve the theme does not work as expected.

**Comment by nbalakin** [comment]
Thanks for feedback.
I've not tested light theme at all, to be honest. :)
I'll fix it in next release. Also you can suggest new "default" colors for light/blue themes.

**Comment by nbalakin** [comment]
@BertTank, what do you think about colors like this:
![vsoe light theme](https://cloud.githubusercontent.com/assets/3763386/11209914/0b9b126e-8d2d-11e5-901e-345b5ec9e2b6.png)

**Comment by BertTank** [comment]
hey @nbalakin thanks  for that quick response! The colors are quite good to read, yes! It seems to me that the green color is a little bit dark in contrast to the others but that's fine, too.

**Comment by nbalakin** [comment]
@BertTank, or something like this:
![vsoe light theme 2](https://cloud.githubusercontent.com/assets/3763386/11212104/53199f5c-8d3c-11e5-842e-3cd06f3eecaa.png)

**Comment by BertTank** [comment]
Just a slight change but indeed a recognizable improvement. I like it :+1:

**Comment by nbalakin** [comment]
Just released 0.4 version with fixed colors for light themes.
