### ISSUE TITLE
Fatal errors are not highlighted as errors

### ISSUE THREAD

**Issue by PazerOP** [nbalakin/VSOutputEnhancer#18]
For example:

`1>c:\users\pazer\onedrive\documents\digipen\cs230\project 7\source\Animation.h(15): fatal error C1083: Cannot open include file: 'IDynamicComponent.h': No such file or directory (compiling source file Source\BehaviorBullet.c)`

is not highlighted with any color.

**Comment by nbalakin** [comment]
Implemented in 1.6.
