### ISSUE TITLE
Have you considered joining efforts with VSColorOutput?

### ISSUE THREAD

**Issue by konste** [nbalakin/VSOutputEnhancer#4]
I wonder if you have seen another open source extension which tries to solve exactly the same problem: https://github.com/mike-ward/VSColorOutput 

Unfortunately there is a problem (which VSColorOutput author claims to be a bug in VS) which makes VSColorOutput barely usable with any color schema other than default. It is discussed here: https://github.com/mike-ward/VSColorOutput/issues/4

It would be great if you find a way to join efforts with Mike and produce One extension which works right with custom VS color schemes. 

Thank you!
Konstantin

**Comment by nbalakin** [comment]
@konste, yep, I've seen it.
And I'm developing my own extension due of that bug with VS 2015 and dark theme.

**Comment by nbalakin** [comment]
I don't think that my code can help to resolve that problem because we use different way to do same features. Mike Ward use a COM API to load custom colors and I use only MEF to do that.

**Comment by konste** [comment]
Oh, wow! Completely new extension to overcome a bug? Well... I'm very interested to see the extension which has the same features as VsColorOutput, but works! I'll see if I can contribute.

**Comment by mike-ward** [comment]
For what it's worth, most people can resolve the color issue in VSColorOuput by simply restarting Visual Studio. Changing colors in the Visual Studio dialog does not raise the notification VSColorOutput needs to reset colors.

The cool part about Open Source is that folks can modify things to fit their needs.

Nice work on the extension. I like your "parser approach". The unit tests are awesome!

**Comment by nbalakin** [comment]
@mike-ward, yep, for me it was resolving with restarting VS too. But it appears something about every third launch of VS and it is very annoying. :(

**Comment by mike-ward** [comment]
I've updated VSColorOutput to resolve the theme issue. Upated the infereface and also made color changes effective without forcing a restart.

I really believed it wasn't possible to fix this until I saw your extension working on my machine. Thanks for convincing me to revisit the issue.

**Comment by konste** [comment]
I'm so glad you guys managed to join your knowledge and experience for everybody's benefit! VSColorOutput 2.1 is just great Xmas present for all developers! Very much appreciate your both hard work and awesome results!
