### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [nbalakin/VSOutputEnhancer#44]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by scottkuhl** [comment]
[Writing Visual Studio Extensions with Mads - Splitting extensions for Visual Studio 2022](https://www.youtube.com/watch?v=-PKIPTW6km0)

**Comment by egorpugin** [comment]
+1

**Comment by clairernovotny** [comment]
@rprouse any interest in updating this for VS 2022? 

@nbalakin are you still maintaining this? If not, should it be forked and published with updates?

**Comment by rprouse** [comment]
@clairernovotny I could make the updates again, but not if they are going to not be released. @nbalakin are you no longer maintaining this? Do you want me to take it over?

**Comment by nbalakin** [comment]
@rprouse, It would be nice.
I'm still maintaining the extension but in very slow pace.

**Comment by drewnoakes** [comment]
FYI I started using https://github.com/mike-ward/VSColorOutput64 (split from https://github.com/mike-ward/VSColorOutput) which has support for VS2022. It seems to be a more active project.

**Comment by clairernovotny** [comment]
@drewnoakes I found the RegEx patterns hard to configure in that one.

**Comment by rprouse** [comment]
@nbalakin I've submitted the PR for your review. I'm not sure I'm ready to take over another project, but if you need me to build this for you so that you just need to upload it, feel free to make me a contributor to this repo and I will create a release and attach the built VSIX.
