### ISSUE TITLE
Debug output color

### ISSUE THREAD

**Issue by jwiemann** [nbalakin/VSOutputEnhancer#5]
I would like to see the Debug output colorized. Important would be the Information/Warning/Error from Trace.

Thanks!

**Comment by nbalakin** [comment]
Just update extension in VS gallery with this feature.
![vsoe debug output](https://cloud.githubusercontent.com/assets/3763386/11503412/1f018dca-9849-11e5-9cd1-a5ee9892bb8d.png)

**Comment by lookforit** [comment]
I can not see this effect in debug output(no color).
With  : 
vs 2015
 locale Chinese

**Comment by nbalakin** [comment]
Hi @lookforit.
I've created new issue #17 so that it'd be easier to track status of this bug.
