### ISSUE TITLE
Major bug: VSOutputEnhancer kills build performance

### ISSUE THREAD

**Issue by konste** [nbalakin/VSOutputEnhancer#8]
It took me awhile to identify the guilty VS extension, but now I'm sure - VSOutputEnhancer is responsible for dramatic slowdown of Visual Studio builds. Normally during the build I can see all 8 cores loaded most of the time. With VSOutputEnhancer active I see that the whole process become serialized, i.e. more or less single threaded. Just try it with solution which contains a hundred projects and takes a few minutes to build and you would notice the difference immediately.

**Comment by nbalakin** [comment]
@konste, I just submit new version of extension on VS gallery. Can you check, did it fix the problem?

**Comment by konste** [comment]
I have not measured it with the clock, but it feels like it does not slow down the build anymore! Thank you!

**Comment by nbalakin** [comment]
@konste, you are welcome. :)
